; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "ModShell"
!define PRODUCT_VERSION "0.1beta1"
!define PRODUCT_PUBLISHER "Pozsar Zsolt"
!define PRODUCT_WEB_SITE "https://pozsarzs.github.io/modshell/"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\modshell.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Language Selection Dialog Settings
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"

; Uninstaller pages
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE "$(MUILicense)" 
!insertmacro MUI_PAGE_COMPONENTS
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!define MUI_FINISHPAGE_RUN "$INSTDIR\modshell.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_WELCOME
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_UNPAGE_FINISH

; Language files
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "Hungarian"

; License Language
LicenseLangString MUILicense ${LANG_ENGLISH} "modshell\LICENCE"
LicenseLangString MUILicense ${LANG_HUNGARIAN} "modshell\LICENCE"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "modshell-0.1beta1-win32.exe"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Function .onInit
  !insertmacro MUI_LANGDLL_DISPLAY
  StrCpy $InstDir "$PROGRAMFILES32\ModShell"
FunctionEnd

Section "Main files" SEC01
  SetOverwrite try

  SetOutPath "$INSTDIR\document"
  File "modshell\document\authors"
  File "modshell\document\changelog"
  File "modshell\document\copyright"
  File "modshell\document\readme.md"
  File "modshell\document\version"

  SetOutPath "$INSTDIR\document\example"
  File "modshell\document\example\adam4018.bat"
  File "modshell\document\example\addition.bat"
  File "modshell\document\example\ansi.bat"
  File "modshell\document\example\arrays.bat"
  File "modshell\document\example\copyset1.bat"
  File "modshell\document\example\copyset2.bat"
  File "modshell\document\example\for-if.bat"
  File "modshell\document\example\getdt510.bat"
  File "modshell\document\example\getpm9c1.bat"
  File "modshell\document\example\getpm9c2.bat"
  File "modshell\document\example\setdt510.bat"

  SetOutPath "$INSTDIR\document\in_brief"
  File "modshell\document\in_brief\ansi.md"
  File "modshell\document\in_brief\dcon.md"
  File "modshell\document\in_brief\hart.md"
  File "modshell\document\in_brief\methods.md"
  File "modshell\document\in_brief\modbus.md"

  SetOutPath "$INSTDIR\document\picture"
  File "modshell\document\picture\modshell-f.png"
  File "modshell\document\picture\modshell.png"
  File "modshell\document\picture\modshell-r.png"
  File "modshell\document\picture\xmodshell-dump.png"
  File "modshell\document\picture\xmodshell-edit.png"
  File "modshell\document\picture\xmodshell-regtable.png"
  File "modshell\document\picture\xmodshell-sercons.png"
  File "modshell\document\picture\xmodshell-varmon.png"

  SetOutPath "$INSTDIR\document\syntax"
  File "modshell\document\syntax\modshell.lang"
  File "modshell\document\syntax\modshell.nanorc"
  File "modshell\document\syntax\modshell.syntax"
  File "modshell\document\syntax\modshell.vim"
  File "modshell\document\syntax\modshell.xml"
  File "modshell\document\syntax\modshell.yaml"
  File "modshell\document\syntax\README.md"
  File "modshell\document\syntax\scripts.vim"
  File "modshell\document\syntax\Syntax"

  SetOutPath "$INSTDIR"
  File "modshell\modshell.exe"
  File "modshell\serialechoserver.exe"
  File "modshell\serialmbmonitor.exe"
  File "modshell\tcpechoserver.exe"
  File "modshell\udpechoserver.exe"
  File "modshell\xmodshell.exe"
  File "modshell\licence"
  File "modshell\readme.md"

  CreateShortCut "$DESKTOP\ModShell.lnk" "$INSTDIR\modshell.exe"
  CreateShortCut "$DESKTOP\XModShell.lnk" "$INSTDIR\xmodshell.exe"
  CreateDirectory "$SMPROGRAMS\ModShell"
  CreateShortCut "$SMPROGRAMS\ModShell\ModShell.lnk" "$INSTDIR\modshell.exe"
  CreateShortCut "$SMPROGRAMS\ModShell\XModShell.lnk" "$INSTDIR\xmodshell.exe"
  CreateShortCut "$SMPROGRAMS\ModShell\SerialEchoServer.lnk" "$INSTDIR\serialechoserver.exe"
  CreateShortCut "$SMPROGRAMS\ModShell\SerialMBMonitor.lnk" "$INSTDIR\serialmbmonitor.exe"
  CreateShortCut "$SMPROGRAMS\ModShell\TCPEchoServer.lnk" "$INSTDIR\tcpechoserver.exe"
  CreateShortCut "$SMPROGRAMS\ModShell\UDPEchoServer.lnk" "$INSTDIR\udpechoserver.exe"
SectionEnd

Section "Translate HU" SEC02
  SetOutPath "$INSTDIR\message\hu"
  File "modshell\message\hu\modshell.mo"
  File "modshell\message\hu\modshell.po"
  File "modshell\message\hu\serialechoserver.mo"
  File "modshell\message\hu\serialechoserver.po"
  File "modshell\message\hu\serialmbmonitor.mo"
  File "modshell\message\hu\serialmbmonitor.po"
  File "modshell\message\hu\tcpechoserver.mo"
  File "modshell\message\hu\tcpechoserver.po"
  File "modshell\message\hu\udpechoserver.mo"
  File "modshell\message\hu\udpechoserver.po"
  File "modshell\message\hu\xmodshell.mo"
  File "modshell\message\hu\xmodshell.po"

  SetOutPath "$INSTDIR\message"
  File "modshell\message\modshell.pot"
  File "modshell\message\serialechoserver.pot"
  File "modshell\message\serialmbmonitor.pot"
  File "modshell\message\tcpechoserver.pot"
  File "modshell\message\udpechoserver.pot"
  File "modshell\message\xmodshell.pot"
SectionEnd

Section -AdditionalIcons
  SetOutPath $INSTDIR
  CreateDirectory "$SMPROGRAMS\ModShell"
  CreateShortCut "$SMPROGRAMS\ModShell\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\modshell.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\modshell.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd

; Section descriptions
  LangString DESC_Section1 ${LANG_ENGLISH} "Required files"
  LangString DESC_Section2 ${LANG_ENGLISH} "Hungarian translate"
  LangString DESC_Section1 ${LANG_HUNGARIAN} "K�telez� �llom�nyok"
  LangString DESC_Section2 ${LANG_HUNGARIAN} "Magyar ford�t�s"
  !insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC01} $(DESC_Section1)
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC02} $(DESC_Section2)
  !insertmacro MUI_FUNCTION_DESCRIPTION_END

; Section uninstall
  Function un.onInit
    !insertmacro MUI_UNGETLANGUAGE
  FunctionEnd

Section Uninstall
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\document\authors"
  Delete "$INSTDIR\document\changelog"
  Delete "$INSTDIR\document\copyright"
  Delete "$INSTDIR\document\example\adam4018.bat"
  Delete "$INSTDIR\document\example\addition.bat"
  Delete "$INSTDIR\document\example\ansi.bat"
  Delete "$INSTDIR\document\example\arrays.bat"
  Delete "$INSTDIR\document\example\copyset1.bat"
  Delete "$INSTDIR\document\example\copyset2.bat"
  Delete "$INSTDIR\document\example\for-if.bat"
  Delete "$INSTDIR\document\example\getdt510.bat"
  Delete "$INSTDIR\document\example\getpm9c1.bat"
  Delete "$INSTDIR\document\example\getpm9c2.bat"
  Delete "$INSTDIR\document\example\setdt510.bat"
  Delete "$INSTDIR\document\in_brief\ansi.md"
  Delete "$INSTDIR\document\in_brief\dcon.md"
  Delete "$INSTDIR\document\in_brief\hart.md"
  Delete "$INSTDIR\document\in_brief\methods.md"
  Delete "$INSTDIR\document\in_brief\modbus.md"
  Delete "$INSTDIR\document\picture\modshell-f.png"
  Delete "$INSTDIR\document\picture\modshell.png"
  Delete "$INSTDIR\document\picture\modshell-r.png"
  Delete "$INSTDIR\document\picture\xmodshell-dump.png"
  Delete "$INSTDIR\document\picture\xmodshell-edit.png"
  Delete "$INSTDIR\document\picture\xmodshell-regtable.png"
  Delete "$INSTDIR\document\picture\xmodshell-sercons.png"
  Delete "$INSTDIR\document\picture\xmodshell-varmon.png"
  Delete "$INSTDIR\document\readme.md"
  Delete "$INSTDIR\document\syntax\modshell.lang"
  Delete "$INSTDIR\document\syntax\modshell.nanorc"
  Delete "$INSTDIR\document\syntax\modshell.syntax"
  Delete "$INSTDIR\document\syntax\modshell.vim"
  Delete "$INSTDIR\document\syntax\modshell.xml"
  Delete "$INSTDIR\document\syntax\modshell.yaml"
  Delete "$INSTDIR\document\syntax\README.md"
  Delete "$INSTDIR\document\syntax\scripts.vim"
  Delete "$INSTDIR\document\syntax\Syntax"
  Delete "$INSTDIR\document\version"
  Delete "$INSTDIR\licence"
  Delete "$INSTDIR\message\hu\modshell.mo"
  Delete "$INSTDIR\message\hu\modshell.po"
  Delete "$INSTDIR\message\hu\serialechoserver.mo"
  Delete "$INSTDIR\message\hu\serialechoserver.po"
  Delete "$INSTDIR\message\hu\serialmbmonitor.mo"
  Delete "$INSTDIR\message\hu\serialmbmonitor.po"
  Delete "$INSTDIR\message\hu\tcpechoserver.mo"
  Delete "$INSTDIR\message\hu\tcpechoserver.po"
  Delete "$INSTDIR\message\hu\udpechoserver.mo"
  Delete "$INSTDIR\message\hu\udpechoserver.po"
  Delete "$INSTDIR\message\hu\xmodshell.mo"
  Delete "$INSTDIR\message\hu\xmodshell.po"
  Delete "$INSTDIR\message\modshell.pot"
  Delete "$INSTDIR\message\serialechoserver.pot"
  Delete "$INSTDIR\message\serialmbmonitor.pot"
  Delete "$INSTDIR\message\tcpechoserver.pot"
  Delete "$INSTDIR\message\udpechoserver.pot"
  Delete "$INSTDIR\message\xmodshell.pot"
  Delete "$INSTDIR\modshell.exe"
  Delete "$INSTDIR\readme.md"
  Delete "$INSTDIR\serialechoserver.exe"
  Delete "$INSTDIR\serialmbmonitor.exe"
  Delete "$INSTDIR\tcpechoserver.exe"
  Delete "$INSTDIR\udpechoserver.exe"
  Delete "$INSTDIR\xmodshell.exe"

  Delete "$DESKTOP\ModShell.lnk"
  Delete "$DESKTOP\XModShell.lnk"
  Delete "$SMPROGRAMS\ModShell\ModShell.lnk"
  Delete "$SMPROGRAMS\ModShell\SerialEchoServer.lnk"
  Delete "$SMPROGRAMS\ModShell\SerialMBMonitor.lnk"
  Delete "$SMPROGRAMS\ModShell\TCPEchoServer.lnk"
  Delete "$SMPROGRAMS\ModShell\UDPEchoServer.lnk"
  Delete "$SMPROGRAMS\ModShell\Uninstall.lnk"
  Delete "$SMPROGRAMS\ModShell\XModShell.lnk"

  RMDir "$SMPROGRAMS\ModShell"
  RMDir "$INSTDIR\message\hu"
  RMDir "$INSTDIR\message"
  RMDir "$INSTDIR\document\example"
  RMDir "$INSTDIR\document\in-brief"
  RMDir "$INSTDIR\document\picture"
  RMDir "$INSTDIR\document\syntax"
  RMDir "$INSTDIR\document"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd
