# $FreeBSD$

PORTNAME=	modshell
PORTVERSION=	0.1alpha2
CATEGORIES=	net
MASTER_SITES=	http://www.pozsarzs.hu/packages/software/modshell/

MAINTAINER=	pozsarzs@gmail.com
COMMENT=	Command-driven scriptable Modbus utility

GNU_CONFIGURE=	yes

.include <bsd.port.mk>

CONFIGURE_ARGS+=stagedir=$(STAGEDIR)/$(PREFIX)
