#!/usr/bin/bash
# +----------------------------------------------------------------------------+
# | ModShell 0.1 * Command-driven scriptable Modbus utility                    |
# | Copyright (C) 2023 Pozsar Zsolt <pozsarzs@gmail.com>                       |
# | convfordos                                                                 |
# | Convert character set of the .po file for DOS                              |
# +----------------------------------------------------------------------------+

NAME=modshell

# Hungarian
LANG=hu
iconv -f utf8 -t cp852 $LANG/$NAME.po > $LANG-cp852/out.po
cat $LANG-cp852/out.po | sed s/"charset=UTF-8"/"charset=cp852"/ > $LANG-cp852/$NAME.po
rm $LANG-cp852/out.po
msgfmt $LANG-cp852/$NAME.po -o $LANG-cp852/$NAME.mo
