.TH SerialMBMonitor 1 "2024 December 03" ""
.SH NAME
serialmbmonitor \- Simple serial Modbus traffic monitor
.SH SYNOPSIS
.B serialmbmonitor
[device] [baudrate] [databit(s)] [parity] [stopbit(s)]
.br
.B serialmbmonitor
[-h|--help|-v|-version]
.SH COPYRIGHT
SerialMBMonitor is Copyright (C) 2024 by Pozsar Zsolt.
.SH DESCRIPTION
This utility is part of ModShell and can be used to decode Modbus/ASCII or RTU
telegrams. The Modshell program's \fImbmon\fP command works the same way,
but it can also be used in DOS. This program is designed for Windows and
Unix-like operating systems.
.SH OPTIONS
.TP
.B \-h \-\-help
Write useable parameters.
.TP
.B \-v \-\-version
Write version and build information.
.TP
.B device
Set serial port name.
.TP
.B baudrate
Set baudrate (150-115200).
.TP
.B databit
Set number of databits (7|8).
.TP
.B parity
Set parity type (e|n|o).
.TP
.B stopbit
Set number of stopbits (1|2).
.SH EXIT STATUS
.TP
.B 0
Normal exit.
.TP
.B 1
Bad command line parameter.
.TP
.B 2
The serial port cannot be opened.
.TP
.B 3
Serial port is locked.
.SH HOMEPAGE
.UR http://www.pozsarzs.hu
.UE
.PP
.UR https://pozsarzs.github.io/modshell
.UE
.PP
.UR https://github.com/pozsarzs/modshell
.UE
.SH SEE ALSO
.PD 0
.LP
\fBmbconv\fP(1)
\fBmodshell\fP(1)
\fBnumconv\fP(1)
\fBserialechoserver\fP(1)
\fBtcpechoserver\fP(1)
\fBudpechoserver\fP(1)
\fBxmodshell\fP(1)
and files in document or /usr/share/doc/modshell/ folder (or equivalent on your system).
.SH AUTHOR
Pozsar Zsolt
.MT pozsarzs@gmail.com
.ME
