.TH UDPEchoServer 1 "2024 December 03" ""
.SH NAME
udpechoserver \- Simple UDP echo server
.SH SYNOPSIS
.B tcpechoserver
[options]
.SH COPYRIGHT
UDPEchoServer is Copyright (C) 2024 by Pozsar Zsolt.
.SH DESCRIPTION
This utility is part of ModShell and can be used to test TCP connectivity. The
program is designed for Windows and Unix-like operating systems.
.SH OPTIONS
.TP
.B \-h \-\-help
Write useable parameters.
.TP
.B \-v \-\-version
Write version and build information.
.TP
.B port
Set port number (0-65535).
.SH EXIT STATUS
.TP
.B 0
Normal exit.
.TP
.B 1
Bad command line parameter.
.TP
.B 2
The socket cannot be opened.
.SH HOMEPAGE
.UR http://www.pozsarzs.hu
.UE
.PP
.UR https://pozsarzs.github.io/modshell
.UE
.PP
.UR https://github.com/pozsarzs/modshell
.UE
.SH SEE ALSO
.PD 0
.LP
\fBmbconv\fP(1)
\fBmodshell\fP(1)
\fBserialechoserver\fP(1)
\fBserialmbmonitor\fP(1)
\fBtcpechoserver\fP(1)
\fBxmodshell\fP(1)
.LP
and files in document or /usr/share/doc/modshell/ folder (or equivalent on your system).
.SH AUTHOR
Pozsar Zsolt
.MT pozsarzs@gmail.com
.ME
