#!/bin/bash
#
# create txz package on Linux
#

NAME="modshell"
RELEASE="1"
VERSION="0.1beta2"

if [ `whoami` != 'root' ]
then echo 'ERROR: You are not root!'; exit
fi

if [ $# -eq 0 ]
then
  read -p "Architecture: " ARCH
else
  ARCH=$1
fi

find $NAME -exec touch {} +
chown -R root:root $NAME
makepkg -c y "../$NAME-$VERSION-$ARCH-$RELEASE.txz"

