#!/bin/bash
#
# create bin and zip package on Linux
#

NAME="modshell"
LABEL="ModShell v0.1-beta1"
VERSION="0.1beta1"
OS="linux"

if [ `whoami` != 'root' ]
then echo 'ERROR: You are not root!'; exit
fi

if [ $# -eq 0 ]
then
  read -p "Architecture: " ARCH
else
  ARCH=$1
fi

find $NAME -exec touch {} +
chown -R root:root $NAME
makeself --keep-umask $NAME "$NAME-$VERSION-$OS-$ARCH.bin" "$LABEL" ./install
zip -r "$NAME-$VERSION-$OS-$ARCH.zip" $NAME
