#!/usr/local/bin/bash
#
# create bin and zip package on FreeBSD
#

NAME="modshell"
LABEL="ModShell v0.1-alpha1"
VERSION="0.1alpha1"
OS="freebsd"

if [ `whoami` != 'root' ]
then echo 'ERROR: You are not root!'; exit
fi

if [ $# -eq 0 ]
then
  read -p "Architecture: " ARCH
else
  ARCH=$1
fi

find $NAME -exec touch {} +
chown -R root:root $NAME
makeself $NAME "$NAME-$VERSION-$OS-$ARCH.bin" "$LABEL" ./install
zip -r "$NAME-$VERSION-$OS-$ARCH.zip" $NAME
