#!/bin/bash
#
# create rpm package on Linux
#

NAME="modshell"
RELEASE="1"
VERSION="0.1beta2"

if [ `whoami` != 'root' ]
then echo 'ERROR: You are not root!'; exit
fi

find BUILDROOT -exec touch {} +
chown -R root:root BUILDROOT
rpmbuild -ba --noclean "SPECS/$NAME-$VERSION-$RELEASE.spec"
setarch i386 rpmbuild -ba --noclean "SPECS/$NAME-$VERSION-$RELEASE.spec"
