#!/bin/bash
#
# create deb package on Linux
#

NAME='modshell'
VERSION='0.1beta2'
RELEASE='1'

if [ $# -eq 0 ]
then
  read -p "Architecture: " ARCH
else
  ARCH=$1
fi

find "${NAME}_${VERSION}-${RELEASE}_${ARCH}" -exec touch {} +
fakeroot dpkg-deb --build "${NAME}_${VERSION}-${RELEASE}_${ARCH}" && lintian "${NAME}_${VERSION}-${RELEASE}_${ARCH}.deb"
